apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-with-prometheus
  labels:
    app: python-with-prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-with-prometheus
  template:
    metadata:
      labels:
        app: python-with-prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
    spec:
      containers:
        - name: python-with-prometheus
          imagePullPolicy: Always
          image: kylos101/python-with-prometheus:0.0.17
          ports:
            - containerPort: 8090
          # Necessary to see stderr output
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
